"""Fixed workout tables

Revision ID: 2e3d363f4097
Revises: 9c81ecc8fb51
Create Date: 2026-04-30 01:45:25.671772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2e3d363f4097'
down_revision: Union[str, Sequence[str], None] = '9c81ecc8fb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('userid', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('image', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'exercises', 'users', ['userid'], ['id'])
    op.add_column('user_progress', sa.Column('date_start', sa.Date(), nullable=True))
    op.add_column('user_progress', sa.Column('date_end', sa.Date(), nullable=True))
    op.drop_column('user_progress', 'date')
    op.add_column('workout_exercises', sa.Column('day_of_week', sa.Integer(), nullable=True))
    op.drop_column('workouts', 'workout_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('workout_type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('workout_exercises', 'day_of_week')
    op.add_column('user_progress', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('user_progress', 'date_end')
    op.drop_column('user_progress', 'date_start')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_column('exercises', 'image')
    op.drop_column('exercises', 'userid')
    # ### end Alembic commands ###
