"""updated user database

Revision ID: c4bff4b264ff
Revises: 942cfe6643a0
Create Date: 2026-03-08 17:23:50.322071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c4bff4b264ff'
down_revision: Union[str, Sequence[str], None] = '942cfe6643a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('lname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.drop_column('users', 'name')
    op.drop_column('users', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'lname')
    op.drop_column('users', 'fname')
    # ### end Alembic commands ###
